#!/usr/bin/env bash
# Writes the plugin registry from every `struct X: KnobPlugin` under KnobsKit/Plugins.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/KnobsKit/Generated/PluginRegistry.generated.swift"
mkdir -p "$(dirname "$out")"

types=$(grep -rhoE '^(public |final )*struct [A-Za-z0-9_]+ *: *[^{]*KnobPlugin' "$root/KnobsKit/Plugins" --include='*.swift' \
  | sed -E 's/.*struct ([A-Za-z0-9_]+).*/\1/' | sort -u || true)

tmp=$(mktemp)
{
  echo "// Generated by scripts/generate-registry.sh. Do not edit."
  echo ""
  echo "public enum PluginRegistry {"
  echo "    public static let all: [any KnobPlugin] = ["
  for type in $types; do echo "        $type(),"; done
  echo "    ]"
  echo "}"
} > "$tmp"

# Rewriting an unchanged file would recompile the framework on every build.
if cmp -s "$tmp" "$out"; then rm "$tmp"; else mv "$tmp" "$out"; fi
